version: '3.8'

services:
  web:
    build: .
    container_name: php-apache-container
    ports:
      - "3000:80"
    volumes:
      - .:/var/www/html
    depends_on: 
      - db
    
  db:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-container
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root

